"""Face Keypoints nodes for ComfyUI"""
from .nodes import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_FACE
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_FACE
from .InstantIDAdvanced import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_INSTANT
from .InstantIDAdvanced import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_INSTANT

# Merge all mappings
NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_FACE,
    **NODE_CLASS_MAPPINGS_INSTANT
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_FACE,
    **NODE_DISPLAY_NAME_MAPPINGS_INSTANT
}

__version__ = "1.0.0"